global:
  scrape_interval:     15s # Default is every 1 minute.
  evaluation_interval: 15s # Default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'observability-example'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]